### PR TITLE
Fix memory leak in `tnt_sbuf_object_grow_stack`

### LINKED ISSUE #139: Memory Leak. Bug
This code causes

Valgrind:
LEAK SUMMARY:
==18960==    definitely lost: 128 bytes in 1 blocks

ASAN shows allocation at  tnt_object.c:78 in tnt_mem_alloc function as leak

```
int main() {
    tnt_stream * f = tnt_object(nullptr);
    tnt_object_add_array(f, 1);
        tnt_object_add_map(f, 1);
            tnt_object_add_str(f, "k", 1);
            tnt_object_add_map(f, 5);
                tnt_object_add_str(f, "a", 1);
                tnt_object_add_array(f, 0);

                tnt_object_add_str(f, "b", 1);
                tnt_object_add_array(f, 0);

                tnt_object_add_str(f, "c", 1);
                tnt_object_add_array(f, 0);

                tnt_object_add_str(f, "d", 1);
                tnt_object_add_array(f, 0);

                tnt_object_add_str(f, "e", 1);
                tnt_object_add_map(f, 1);
                    tnt_object_add_str(f, "k", 1);
                    tnt_object_add_array(f, 2);
                        tnt_object_add_str(f, "k", 1);
                        tnt_object_add_str(f, "k", 1);

    tnt_stream_free(f);
}
```

### PR DESCRIPTION
**Pull request by EvgenyMekhanik**
Fixed memory leak in `tnt_sbuf_object_grow_stack` function.
Fixed SIGSEGV in case when memory allocation failure in `tnt_object` function.

Closes #139

### CODE REVIEW

File: test/cli/tarantool_leak.c [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+        tnt_stream_free(stream);
+
+        return check_plan();
+}
+
+int main()
+{
+        test_leak();
+        return 0;
+}
```
Comment (locker) [inline test/cli/tarantool_leak.c:52]: Writing a test that always passes is bad. IMO better mock the allocation function. The allocation function used by the connector is already virtual so you could replace it in the test to account memory.

**Review by locker — CHANGES_REQUESTED** [review]

File: test/CMakeLists.txt [hunk 2]
```diff
@@ -2,6 +2,8 @@ add_library(test_common STATIC "${CMAKE_CURRENT_SOURCE_DIR}/common/test.c"
                                "${CMAKE_CURRENT_SOURCE_DIR}/common/common.c"
                                "${CMAKE_CURRENT_SOURCE_DIR}/common/tnt_assoc.c")
 
+set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -g -fsanitize=address -fsanitize=leak")
+
```
[the remark this answers is not in the document]
Comment (EvgenyMekhanik) [reply test/CMakeLists.txt:6]: you should download it unsig git submodule --init --recursive. I can add this in cmake!

[the remark this answers is not in the document]
Comment (EvgenyMekhanik) [reply test/CMakeLists.txt:6]: as i see there is no CI for this project... i can add check for sanitizer in cmake or i should add CI builds also?

[the remark this answers is not in the document]
Comment (locker) [reply test/CMakeLists.txt:6]: git-submodule helps, thanks. But 'make test' still doesn't work:

```
$ make test
Traceback (most recent call last):
  File "./test-run.py", line 57, in <module>
    import lib
  File "/home/vlad/src/tarantool-c/test-run/lib/__init__.py", line 6, in <module>
    from lib.tarantool_server import TarantoolServer
  File "/home/vlad/src/tarantool-c/test-run/lib/tarantool_server.py", line 2, in <module>
    import gevent
ImportError: No module named gevent
```

I have python3-gevent installed, but looks like python2 version is required, which isn't available on my distribution (Ubuntu). Looks like we need to update the submodule.

[the remark this answers is not in the document]
Comment (EvgenyMekhanik) [reply test/CMakeLists.txt:6]: remove this from CMake and create issue https://github.com/tarantool/tarantool-c/issues/149

File: test/cli/tarantool_leak.c (hunk 1 above)
Comment (EvgenyMekhanik) [reply test/cli/tarantool_leak.c]: Fixed, implement function which saves allocated pointers in std:set. In test i check that set is empty after resource release.

File: test/CMakeLists.txt (hunk 2 above)
[the remark this answers is not in the document]
Comment (EvgenyMekhanik) [reply test/CMakeLists.txt:8]: Fix this test and update test-run

File: test/cli/tarantool_poll.c [hunk 3]
```diff
@@ -91,8 +91,10 @@ test_poll() {
 	is(1, ok, "expected non-assert test");
 
 	while (last > -1) {
-		if (streams[last] != NULL)
+		if (streams[last] != NULL) {
 			tnt_close(streams[last]);
+			tnt_stream_free(streams[last]);
+		}
```
Comment (locker) [inline test/cli/tarantool_poll.c:97]: Please revert all changes unrelated to the fix. They belong to the future PR enabling ASAN.

**Review by locker — CHANGES_REQUESTED** [review]

File: test/cli/tarantool_poll.c (hunk 3 above)
Comment (EvgenyMekhanik) [reply test/cli/tarantool_poll.c]: fixed, after this review i create new PR wth this changes and enabling ASAN

File: test/cli/tarantool_leak.cc [hunk 4]
```diff
@@ -0,0 +1,78 @@
...
+#include <tarantool/tarantool.h>
+#include <tarantool/tnt_net.h>
+#include <tarantool/tnt_opt.h>
+#include <msgpuck.h>
+
+#include "common.h"
+
+const char template_msgpuck[] = "[{\"m\": {\"m\": [], \"m\": [], \"m\": [], \"m\": [], \"m\": {\"m\": [\"a\", \"a\"]}}}]";
+
+static std::set<void *> allocations;
```
[the remark this answers is not in the document]
Comment (EvgenyMekhanik) [reply test/cli/tarantool_leak.cc]: Fixed

**Review by locker — APPROVED** [review]

File: test/cli/tarantool-leak.result [hunk 5]
```diff
@@ -0,0 +1,5 @@
+TAP version 13
```
Comment (Totktonada) [inline test/cli/tarantool-leak.result:1]: Neither of the result files are necessary, because all of them contain a result in the TAP13 format: test-run knows how to check it.

File: test/cli/tarantool_leak.c [hunk 6]
```diff
@@ -0,0 +1,81 @@
...
+	ok(!strcmp(data, template_msgpuck), "Check the created msgpuck");
+	tnt_stream_free(stream);
+	ok(alloc_size == 0, "Check memory leak absence");
+	return check_plan();
+}
+
+int main()
+{
+	test_leak();
+	return 0;
```
Comment (Totktonada) [inline test/cli/tarantool_leak.c:80]: AFAIU, it is the rule of thumb to give a non-zero exit code if a test fails. I would use the `check_plan()` as the exit code. (In theory it'll even allow us to change a testing harness to something simpler.)

**Review by Totktonada — APPROVED** [review]
LGTM.

I have a few minor comments, they are very optional.

File: test/cli/tarantool_leak.c (hunk 6 above)
Comment (EvgenyMekhanik) [reply test/cli/tarantool_leak.c]: fixed

File: test/cli/tarantool-leak.result (hunk 5 above)
Comment (EvgenyMekhanik) [reply test/cli/tarantool-leak.result:1]: I add them because tests not passed without them.

Comment (Totktonada) [reply test/cli/tarantool-leak.result]: Evgeny re-checked and removed them.
